### ISSUE TITLE
Add client config `request_timeout`

### ISSUE THREAD

**Issue by amaurym** [dizda/fast-socks5#11]
I saw there's a `request_timeout` on the server config, that makes sense.

However, I think it can be useful to also set a client config `request_timeout`. So basically, if the client on is set, then take that as timeout, or else default to the server config's `request_timeout`.

Does that make sense to add to this lib?

**Comment by dizda** [comment]
Hey @amaurym,

Yes it does make sense, feel free to send a PR.

**Comment by GlenDC** [comment]
I'm sending a PR your wait. Defintely something that I would like to have as well.
