### ISSUE TITLE
Cargo.lock file missing

### ISSUE THREAD

**Issue by PAI5REECHO** [dizda/fast-socks5#14]
[Binary applications _should_ include a `Cargo.lock` file](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries)

**Comment by GlenDC** [comment]
This is a library though, so doesn't apply I would argue.

**Comment by dizda** [comment]
Shall we close this issue?

**Comment by GlenDC** [comment]
I did not create the issue, but that does seem fair to me.

**Comment by PAI5REECHO** [comment]
I guess the example bins are just meant to be examples and not usable servers, sorry

**Comment by dizda** [comment]
No problem. Thanks for bringing that up anyway.
