### ISSUE TITLE
There is a bug in udp support

### ISSUE THREAD

**Issue by enp6** [dizda/fast-socks5#32]
cargo run -- --listen-addr 0.0.0.0:5000 password -u 111 -p 333

In the code, I have written config.set_udp_support(true);

However, it still cannot support UDP and prompts "invalid reply ip"

**Comment by ddscentral** [comment]
Sorry for necro. Yes, the example does not appear to work with UDP.
I got it working with a small hack to src/server.rs but it's not of PR quality. Can post if anyone needs it.

**Comment by dizda** [comment]
Thanks for posting this, have you found a workaround? /cc. @yuguorui @erebe @XOR-op

**Comment by erebe** [comment]
I don't know, I use this crate as a lib and don't use the implemented server/client.
For UDP, I have a special case where I return the bind addr of the udp server I spawn.
https://github.com/erebe/wstunnel/blob/main/src/socks5.rs#L116

**Comment by ddscentral** [comment]
Here's a (very) rough patch which makes UDP work for me in the server example. It does some need cleanup and an extra "rand" dependency.
[fast-socks-udpfix.patch](https://github.com/dizda/fast-socks5/files/14122839/fast-socks-udpfix.patch)

I am a developer but not very familiar with intricacies of Rust. Maybe this patch will at least give you an idea on why the current implementation doesn't work.

**Comment by erebe** [comment]
Does this works if you try to contact your udp socks5 from another machine ?
```
IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0))
```

**Comment by ddscentral** [comment]
You mean outside of localhost ? 
Yes, it does work fine. I run [tun2socks](https://github.com/xjasonlyu/tun2socks) on the client machine. DNS works fine over UDP.

**Comment by yuguorui** [comment]
> Thanks for posting this, have you found a workaround? /cc. @yuguorui @erebe @XOR-op

Yeah, it is hard to set a `reply_ip` without the knowledge of underlay socket.

There is an API `set_reply_ip()` at https://github.com/dizda/fast-socks5/blob/master/src/server.rs#L292. Could you @enp6   please set an IP with this API?

**Comment by yuguorui** [comment]
And here is the comments about the API.
```
    /// Set the bind IP address in Socks5Reply.
    ///
    /// Only the inner socket owner knows the correct reply bind addr, so leave this field to be
    /// populated. For those strict clients, users can use this function to set the correct IP
    /// address.
    ///
    /// Most popular SOCKS5 clients [1] [2] ignore BND.ADDR and BND.PORT the reply of command
    /// CONNECT, but this field could be useful in some other command, such as UDP ASSOCIATE.
    ///
    /// [1]. https://github.com/chromium/chromium/blob/bd2c7a8b65ec42d806277dd30f138a673dec233a/net/socket/socks5_client_socket.cc#L481
    /// [2]. https://github.com/curl/curl/blob/d15692ebbad5e9cfb871b0f7f51a73e43762cee2/lib/socks.c#L978
```

**Comment by ddscentral** [comment]
Well setting the reply IP to all zeros (instead of IPv6 localhost) and a random port instead of a zero port seems to work.
But I'm not entirely sure whether this is the correct way to do it, my guess is it isn't or definitely not the best.

**Comment by yuguorui** [comment]
Agreed, but unfortunately RFC 1928 does not have a detailed description for this part.

**Comment by ddscentral** [comment]
By "udp client" you mean the "client" example ?

**Comment by mokeyish** [comment]
Yeah, It only has TCP client exmaple.

**Comment by osousa** [comment]
Does UDP work?  Would be nice as most rust based socks5 servers don't support UDP

**Comment by ddscentral** [comment]
With a small modification I've posted before, UDP does work for me, at least with tun2socks as client.

**Comment by valpackett** [comment]
The server example now can enable UDP (you need to pass the reply IP as a flag) and there's a UDP client example as well (makes a DNS query).
