### ISSUE TITLE
Using in embedded scenario

### ISSUE THREAD

**Issue by abhishekmaha23** [dizda/fast-socks5#38]
Would it be possible to use this library in an embedded setting with no_std?
I have a scenario where I'd like to use it in a low-power environment.

**Comment by dizda** [comment]
Hey @abhishekmaha23 thanks for your interests!

As of today we rely on std lib, unless there's a lot of modification, I think it may require a lot of changes among the source code to make it no_std.

**Comment by abhishekmaha23** [comment]
Sounds like an interesting challenge :)
Thanks for your prompt response, I'll try to fork and give it a shot!
The issue can be closed.
