### ISSUE TITLE
Dumb question: But how to compile/build this

### ISSUE THREAD

**Issue by m4st3rh4nd** [dizda/fast-socks5#53]
`cargo build` "`builds`" something but i cant find any exec. Moving lib.rs, server.rs, client.rs to bin/ gives me Errors. Renaming server.rs/client.rs to main.rs gives me an error from lib.rs
😢

**Comment by dizda** [comment]
try to run `cargo build --example client` or server

**Comment by m4st3rh4nd** [comment]
![image](https://github.com/user-attachments/assets/7b92fc68-7dc2-4ac1-8aed-ed1b249b52b8)
